Repository ManageIQ/manageiq-providers-autosde, pull requests merged in 2020-10, with the labels that each got.

#27 Fix ems refresh following commit 387abe2
  app/models/manageiq/providers/autosde/storage_manager.rb
Labels: bug

#29 Cancelled debugging output of passwords when creating storage-manager.
  app/models/manageiq/providers/autosde/storage_manager/autosde_client.rb
Labels: bug

#33 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#34 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-autosde.gemspec
Labels: developer, enhancement

#38 Implementing remove physical storage
  app/models/manageiq/providers/autosde/storage_manager/physical_storage.rb
Labels: enhancement

#40 Revert "Merge pull request #36 from agrare/revert_use_manageiq_style"
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-autosde.gemspec
Labels: developer, enhancement

#46 Remove unused scaffolding Vm class
  app/models/manageiq/providers/autosde/storage_manager/vm.rb
Labels: technical debt
