Repository ManageIQ/manageiq-providers-autosde, pull requests merged in 2021-09, with the labels that each got.

#79 Added support of bulk-creation of volumes
  app/models/manageiq/providers/autosde/storage_manager/cloud_volume.rb
Labels: enhancement

#80 Added minimum volume size validation on volume update
  app/models/manageiq/providers/autosde/storage_manager/cloud_volume.rb
Labels: bug, morphy/yes?

#85 Added ability do unmap volume from host
  app/models/manageiq/providers/autosde/storage_manager/volume_mapping.rb
Labels: enhancement, morphy/yes?

#78 Convert cloud volume operations to SupportsFeatureMixin
  app/models/manageiq/providers/autosde/storage_manager/cloud_volume.rb
Labels: technical debt

#81 Add support for creating multiple host initiators wwpn
  app/models/manageiq/providers/autosde/storage_manager/host_initiator.rb
Labels: enhancement

#74 Add support for FC WWPN candidates
  app/models/manageiq/providers/autosde/inventory/collector/storage_manager.rb
  app/models/manageiq/providers/autosde/inventory/parser/storage_manager.rb
  app/models/manageiq/providers/autosde/inventory/persister/storage_manager.rb
  spec/models/manageiq/providers/autosde/inventory_spec.rb
  spec/models/manageiq/providers/autosde/wwpn_candidates_spec.rb
  spec/vcr_cassettes/ems_refresh.yml
  spec/vcr_cassettes/get_storage_systems_wwpn_candidates.yml
Labels: enhancement

#94 Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472
  .travis.yml
Labels: test
