Repository ManageIQ/manageiq-providers-autosde, pull requests merged in 2021-03, with the labels that each got.

#62 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#63 Add CODEOWNERS
  .github/CODEOWNERS
Labels: developer

#55 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-autosde_storage_manager_refresh.target
  build/systemd_units/manageiq-providers-autosde_storage_manager_refresh@.service
Labels: technical debt
