Repository ManageIQ/manageiq-providers-autosde, pull requests merged in 2021-11, with the labels that each got.

#102 Support Host Initiator Group(cluster) volume mapping - server part
  app/models/manageiq/providers/autosde/inventory/collector/storage_manager.rb
  app/models/manageiq/providers/autosde/inventory/parser/storage_manager.rb
  app/models/manageiq/providers/autosde/inventory/persister/storage_manager.rb
  app/models/manageiq/providers/autosde/storage_manager/cluster_volume_mapping.rb
  app/models/manageiq/providers/autosde/storage_manager/host_volume_mapping.rb
  app/models/manageiq/providers/autosde/storage_manager/volume_mapping.rb
  spec/models/manageiq/providers/autosde/inventory_spec.rb
  spec/vcr_cassettes/ems_refresh.yml
Labels: enhancement

#109 Creation of host initiator group
  app/models/manageiq/providers/autosde/storage_manager/host_initiator_group.rb
Labels: enhancement

#107 add targeted refresh for editing cloud-volumes and physical-storages
  app/models/manageiq/providers/autosde/inventory/collector/storage_manager.rb
  app/models/manageiq/providers/autosde/inventory/collector/target_collection.rb
  app/models/manageiq/providers/autosde/inventory/parser/storage_manager.rb
  app/models/manageiq/providers/autosde/inventory/persister/storage_manager.rb
  app/models/manageiq/providers/autosde/inventory/persister/target_collection.rb
  app/models/manageiq/providers/autosde/storage_manager/cloud_volume.rb
  app/models/manageiq/providers/autosde/storage_manager/physical_storage.rb
Labels: enhancement

#111 Move boilerplate persister definitions to core
  app/models/manageiq/providers/autosde/inventory/parser/storage_manager.rb
  app/models/manageiq/providers/autosde/inventory/persister/definitions/cloud_collections.rb
  app/models/manageiq/providers/autosde/inventory/persister/storage_manager.rb
  app/models/manageiq/providers/autosde/storage_manager.rb
Labels: refactoring

#112 Improve AutoSDE Refresher Specs
  app/models/manageiq/providers/autosde/inventory/persister/storage_manager.rb
  app/models/manageiq/providers/autosde/inventory/persister/target_collection.rb
  app/models/manageiq/providers/autosde/storage_manager.rb
  spec/models/manageiq/providers/autosde/inventory_spec.rb
  spec/models/manageiq/providers/autosde/storage_manager/refresher_spec.rb
Labels: test
