Repository ManageIQ/manageiq-providers-autosde, pull requests merged in 2022-07, with the labels that each got.

#151 EventCatcher worker for Physical Storage
  app/models/manageiq/providers/autosde/storage_manager.rb
  app/models/manageiq/providers/autosde/storage_manager/event_catcher.rb
  app/models/manageiq/providers/autosde/storage_manager/event_catcher/runner.rb
  app/models/manageiq/providers/autosde/storage_manager/event_catcher/stream.rb
  config/settings.yml
  systemd/manageiq-providers-autosde_storage_manager_event_catcher.target
  systemd/manageiq-providers-autosde_storage_manager_event_catcher@.service
Labels: enhancement

#155 Removing meoization
  app/models/manageiq/providers/autosde/storage_manager.rb
Labels: bug

#153 convert to SupportsFeatureMixin
  app/models/manageiq/providers/autosde/storage_manager.rb
Labels: technical debt

#154 display events for physical storage
  app/models/manageiq/providers/autosde/storage_manager/event_catcher/runner.rb
  config/settings.yml
Labels: enhancement
