Repository ManageIQ/manageiq-providers-autosde, pull requests merged in 2022-03, with the labels that each got.

#138 call targeted refresh for ph_storage create and delete
  app/models/manageiq/providers/autosde/storage_manager/physical_storage.rb
Labels: enhancement

#140 remove variables leading underscores from PhysicalStorage class
  app/models/manageiq/providers/autosde/storage_manager/physical_storage.rb
Labels: cleanup

#141 Remove the unnecessary console methods
  app/models/manageiq/providers/autosde/storage_manager.rb
Labels: cleanup

#144 Fix Rspecs
  spec/models/manageiq/providers/autosde/storage_manager/refresher_spec.rb
  spec/vcr_cassettes/bad_token_get_storage_systems_with_relogin_not_fails.yml
  spec/vcr_cassettes/ems_refresh.yml
  spec/vcr_cassettes/get_services.yml
  spec/vcr_cassettes/get_storage_resources.yml
  spec/vcr_cassettes/get_storage_system.yml
  spec/vcr_cassettes/get_storage_systems_autosde_client.yml
  spec/vcr_cassettes/get_storage_systems_from_storage_manager.yml
Labels: dependencies, test

#143 get error data and return error response error
  app/models/manageiq/providers/autosde/storage_manager/autosde_client.rb
Labels: bug
