Repository ManageIQ/manageiq-providers-autosde, pull requests merged in 2022-11, with the labels that each got.

#189 return error when there is no 'response_body'
  app/models/manageiq/providers/autosde/storage_manager/autosde_client.rb
Labels: bug, oparin/yes?

#190 Use postgresql:13 image for ci
  .github/workflows/ci.yaml
Labels: test

#191 Use Job#signal_start when creating EmsRefreshWorkflow
  app/models/manageiq/providers/autosde/storage_manager/cloud_volume.rb
  app/models/manageiq/providers/autosde/storage_manager/host_initiator.rb
  app/models/manageiq/providers/autosde/storage_manager/physical_storage.rb
  app/models/manageiq/providers/autosde/storage_manager/volume_mapping.rb
Labels: refactoring
