Repository ManageIQ/manageiq-providers-autosde, pull requests merged in 2022-08, with the labels that each got.

#158 Update storage system args
  app/models/manageiq/providers/autosde/storage_manager/physical_storage.rb
  spec/models/manageiq/providers/autosde/storage_manager/refresher_spec.rb
  spec/vcr_cassettes/ems_refresh.yml
Labels: enhancement

#157 Sde 460 volume service catalog
  app/models/manageiq/providers/autosde/storage_manager.rb
Labels: enhancement

#159 Fix autosde overwriting generic catalog type
  app/models/manageiq/providers/autosde/storage_manager.rb
Labels: bug

#162 change names of calls to StorageHostsMappingApi
  app/models/manageiq/providers/autosde/inventory/collector/storage_manager.rb
  app/models/manageiq/providers/autosde/storage_manager/volume_mapping.rb
  manageiq-providers-autosde.gemspec
Labels: refactoring

#171 append event.fixed value to event.event_type
  app/models/manageiq/providers/autosde/storage_manager/event_catcher/runner.rb
Labels: enhancement

#173 Fix deprecated `Module#parent` in EventCatcher
  app/models/manageiq/providers/autosde/storage_manager/event_catcher/runner.rb
Labels: bug, oparin/yes?
