Repository ManageIQ/manageiq-providers-autosde, pull requests merged in 2023-02, with the labels that each got.

#199 Added post refresh function to fill empty event columns
  app/models/manageiq/providers/autosde/storage_manager.rb
  app/models/manageiq/providers/autosde/storage_manager/refresher.rb
Labels: bug

#203 storage service resource attachment collection
  app/models/manageiq/providers/autosde/inventory/collector/storage_manager.rb
  app/models/manageiq/providers/autosde/inventory/collector/target_collection.rb
  app/models/manageiq/providers/autosde/inventory/parser/storage_manager.rb
  app/models/manageiq/providers/autosde/inventory/persister/storage_manager.rb
  app/models/manageiq/providers/autosde/storage_manager.rb
  app/models/manageiq/providers/autosde/storage_manager/storage_service_resource_attachment.rb
  spec/models/manageiq/providers/autosde/storage_manager/refresher_spec.rb
  spec/models/manageiq/providers/autosde/storage_manager/refresher_spec_v2.rb
  spec/vcr_cassettes/ems_refresh_v1.yml
  spec/vcr_cassettes/ems_refresh_v2.yml
  spec/vcr_cassettes/get_storage_service_resource_attachments_v1.yml
  spec/vcr_cassettes/get_storage_service_resource_attachments_v2.yml
Labels: enhancement

#200 storage service endpoint
  app/models/manageiq/providers/autosde/inventory/collector/target_collection.rb
  app/models/manageiq/providers/autosde/storage_manager.rb
  app/models/manageiq/providers/autosde/storage_manager/storage_service.rb
  manageiq-providers-autosde.gemspec
Labels: enhancement

#206 Added default option to volume creation mode
  app/models/manageiq/providers/autosde/storage_manager/cloud_volume.rb
Labels: enhancement

#211 [PETROSIAN] Lock the petrosian release branch to test with ruby 3.0
  .github/workflows/ci.yaml
Labels: test

#201 refresh bulk of volumes and get object_id as array
  app/models/manageiq/providers/autosde/storage_manager/ems_refresh_workflow.rb
  manageiq-providers-autosde.gemspec
Labels: wip

#215 Ofer/727285 implement clone
  app/models/manageiq/providers/autosde/storage_manager/cloud_volume.rb
Labels: enhancement
