Repository ManageIQ/manageiq-providers-autosde, pull requests merged in 2024-02, with the labels that each got.

#242 Drop require_nested
  app/models/manageiq/providers/autosde/inventory.rb
  app/models/manageiq/providers/autosde/inventory/collector.rb
  app/models/manageiq/providers/autosde/inventory/parser.rb
  app/models/manageiq/providers/autosde/inventory/persister.rb
  app/models/manageiq/providers/autosde/storage_manager.rb
  app/models/manageiq/providers/autosde/storage_manager/event_catcher.rb
  app/models/manageiq/providers/autosde/storage_manager/refresh_worker.rb
Labels: technical debt, rails7

#243 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#244 drop use of unsupported_reason_add
  app/models/manageiq/providers/autosde/storage_manager/cloud_volume.rb
  app/models/manageiq/providers/autosde/storage_manager/host_initiator_group.rb
  app/models/manageiq/providers/autosde/storage_manager/physical_storage.rb
  app/models/manageiq/providers/autosde/storage_manager/volume_mapping.rb
Labels: refactoring

#245 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1
